# Technique 1 of 4 - Zero-Shot Prompting

# Zero-shot prompting means asking the AI to perform a task
# without giving examples in the prompt.

from groq_client import client

# Send a request to the AI model.
response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {
            "role": "user",
            "content": "Classify as positive or negative: 'The battery life is amazing!'"
        }
    ],
)
# print(response)

# Get the text generated by the AI.
print(response.choices[0].message.content)
# -> Positive